#!/usr/bin/env sh

set -e

usage() {
  echo "usage: git versioning <subcommand>"
  echo
  echo "Available subcommands are:"
  echo "current"
  echo "next"
}

version() {
  echo "versioning git plugin v0.1.0"
  echo
}

error() {
  echo 'Error occurred'
  exit 1
}

trap error ERR

main() {
  trap error ERR

  if [ "$#" -lt 1 ]; then
    usage; exit 1
  fi

  local subcommand="$1"; shift

  case $subcommand in
    "-h"|"--help")
      usage; exit 0
      ;;
    "-v"|"--version")
      version; exit 0
      ;;
  esac

  local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
  if [ ! -e "$workingdir/git-versioning-$subcommand" ]; then
    usage; exit 1
  fi

  source "$workingdir/git-versioning-$subcommand"

  if ! type "cmd_$subcommand" 2&> /dev/null; then
    usage; exit 1
  fi

  cmd_$subcommand "$@"
}

main "$@"
